{% set name = "quickle" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b42b07c8ccb1340c89d3e7a85a09441a839e2afad791f13c19cb849139edee97

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - quickle

about:
  home: https://jcristharif.com/quickle/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A quicker pickle
  description: |
    A fast and small serialization format for a subset of Python types. It's
    based off of pickle, but includes several optimizations and extensions.
  doc_url: https://jcristharif.com/quickle/
  dev_url: https://github.com/jcrist/quickle

extra:
  recipe-maintainers:
    - jcrist
